### PR TITLE
Added rough draft of watch_face script 

### PR DESCRIPTION
**Pull request by davidskeck**
Added script to automatically generate new watch faces from the command line.
Updated template file to add missing includes and correct the placeholder in memset.

Let me know if this is along the lines of what you were thinking in #42.

I'd love any suggestions to improve this code as well. Thank you!

### CODE REVIEW

**Comment by davidskeck** [comment]
Some context for the adding of a newline to the template files: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

**Comment by joeycastillo** [comment]
This sparks so much joy. Thank you for doing this! I don't have any significant comments; just tested it here, and it works great. 😄

**Comment by joeycastillo** [comment]
Actually, one thing occurred to me just after merging: we can autopopulate the year, it doesn't need to be a command line argument. I just went ahead and [made the change here](https://github.com/joeycastillo/Sensor-Watch/commit/5d5e5b125a383174f1891d37498415cc10fe84fe). 

We could also probably autopopulate the author by parsing `git config --list`, but that seems a bit creepy and probably has some privacy implications. 🙃

**Comment by davidskeck** [comment]
Excellent! I'm so glad you found it useful.

I thought of the year thing, but forgot about it when I started implementing things! Good call. I agree on the author thing -- I thought of that too, but decided against it for the same reason.

I have a couple more ideas to improve the script (mainly adding output to say what files were changed/added and their locations), which I'll add in a separate PR.

Thanks for this project! It is super fun.

**Pull request merged**
