### PR TITLE
Add lander game, prime_clock_face, binary_clock_face

### PR DESCRIPTION
**Pull request by KlingonJane**
Prime clock face updates the time display only when the 5 or 6 digit total time is prime.
Example:
10:34:51 is displayed as 103,451 is a prime number.
Six seconds later....
The display updates to 10:34:57 as 103,457 is the next prime number.

Binary watch face has four display modes:
- binary hours and minutes
- binary minutes and seconds
- decimal hours, minutes and seconds ( simple clock face )
- decimal hours, minutes and randomized seconds ( silly clock face )

### CODE REVIEW

**Comment by matheusmoreira** [comment]
Hello! Please break up each watch face into a separate pull request so that they can be reviewed and merged independently.

**Comment by KlingonJane** [comment]
Hi!  Okay, will do.  Thanks for all the great work you are all doing.

**Comment by voloved** [comment]
I've been playing the lander game, btw and it's a lot of fun!

**Comment by KlingonJane** [comment]
Thanks for the feedback!  Will break up into individual pull requests.

**Pull request closed without merging**
