### PR TITLE
Change 24 h with alarm

### PR DESCRIPTION
**Pull request by voloved**
The original Casio F-91W swaps between 24H mode by pressing the `ALARM` button.  
This PR does the same both on the `simple_clock_face` and the `clock_face`.  

`clock_face` will ignore this if `CLOCK_FACE_24H_ONLY` is set on make.

24h

### CODE REVIEW

**Comment by voloved** [comment]
joeycastillo — Today at 4:55 PM
yeah i tend to agree, there are folks who feel.... strongly........ that their watch should never leave 24 hour mode. i'd venture that this feature on the original casio is an annoyance that folks just have to put up with

devolov — Today at 6:14 PM
I though that's what the CLOCK_FACE_24H_ONLY flag in make is for.
I saw clock_face uses it, but nothing else. I just added in a more global usage of that flag into the PR.
In my PR, if that flag is defined, pressing the alarm button doesn't toggle.
Also:
The preferences will no longer show the 24H toggle page
movement_state.settings.bit.clock_mode_24h will be set to true so any other items in the watch will also use 24H mode

joeycastillo — Today at 6:17 PM
It is, I'm just saying, I'm not wild about the UX of having that button toggle 24H mode in the simple watch face. It's a major change from how Sensor Watch has always worked, and on the one face that most everyone uses. Putting it in the settings menu was a choice, not an omission.

**Comment by voloved** [comment]
joeycastillo — Today at 4:55 PM
yeah i tend to agree, there are folks who feel.... strongly........ that their watch should never leave 24 hour mode. i'd venture that this feature on the original casio is an annoyance that folks just have to put up with

devolov — Today at 6:14 PM
I though that's what the CLOCK_FACE_24H_ONLY flag in make is for.
I saw clock_face uses it, but nothing else. I just added in a more global usage of that flag into the PR.
In my PR, if that flag is defined, pressing the alarm button doesn't toggle.
Also:
The preferences will no longer show the 24H toggle page
movement_state.settings.bit.clock_mode_24h will be set to true so any other items in the watch will also use 24H mode

joeycastillo — Today at 6:17 PM
It is, I'm just saying, I'm not wild about the UX of having that button toggle 24H mode in the simple watch face. It's a major change from how Sensor Watch has always worked, and on the one face that most everyone uses. Putting it in the settings menu was a choice, not an omission.

**Review by matheusmoreira — COMMENTED** [review]
It's my understanding that this probably won't be merged due to the watch's UX design concerns but still I'd like to say that the implementation looks good to me, especially the changes to `clock_face` which is the one I'm most familiar with. Thanks for your contribution.

**Comment by voloved** [comment]
Thanks!
I actually made it so that is a toggle in the makefile, piggybacking off `CLOCK_FACE_24H_ONLY `.

```
# CLOCK_FACE_24H_ONLY = X
#  TOGGLE = Pressing the alarm button on the clock face toggles between 24H and 12H
#  YES = Always 24H mode
#  NO = 24H mode can be set in the settings
ifndef CLOCK_FACE_24H_ONLY
CLOCK_FACE_24H_ONLY := NO 
endif
ifeq ($(CLOCK_FACE_24H_ONLY), TOGGLE)
CFLAGS += -DCLOCK_FACE_24H_TOGGLE
else ifeq ($(CLOCK_FACE_24H_ONLY), YES)
CFLAGS += -DCLOCK_FACE_24H_ONLY
else ifneq ($(CLOCK_FACE_24H_ONLY), NO)
$(error CLOCK_FACE_24H_ONLY must be TOGGLE, YES, or NO if used.)
endif
```

**Pull request closed without merging**
