### PR TITLE
introduce github actions

### PR DESCRIPTION
**Pull request by willianpaixao**
Hi @joeycastillo,

This is still a draft. My goals are:

- [x] Have a build pipeline triggered on every push. This pipeline will run a linter, compile the library, and future tests.
- [ ] Upon tag creation, a publish pipeline can be triggered and it will generate a tarball with the compiled library.
- [x] (Optional) A pipeline that builds the Doxygen documentation and publishes it in [Github pages](https://pages.github.com/).

I'm using [ARM Mbed's official docker image](https://os.mbed.com/docs/mbed-os/v6.15/build-tools/docker.html) that already contains all necessary dependencies.

**NOTE**: the directories in `apps/` have spaces and that makes it a little complicated to reference. I kindly ask to rename the folder replacing spaces for possibly dashes or underscores. That's why this PR only compiles `apps/beats-time`.

### CODE REVIEW

**Comment by joeycastillo** [comment]
This is a great pull request, thank you for doing this! I've gone ahead and renamed the projects in the apps folder to remove the spaces, and in a separate commit, fixed the missing prototype warnings in the watch library and the watch apps. 

Super open to all of this. Two thoughts:

1. In terms of build artifacts, I think the only ones that really matter are `movement` and maybe `starter-project`. Most of the other things  in `apps` are tests, demos or works in progress. Probably makes sense to build them, but not to publish them as "releases" per se.
3. If Doxygen's output directory is `docs` at the root of this repo, I think we can publish to GitHub Pages directly from this repo.

**Comment by willianpaixao** [comment]
Hi again @josecastillo,
I intended to finish this PR earlier but this week was very busy. I'm proud to say that I'm quite happy with these pipelines.
Some notes:

- For testing purposes, the GitHub Pages pipeline is triggered in every push. In reality, it should be only triggered upon merging to main branch. So after this PR is merged, lines 3~6 in `gh.pages.yml` should be uncommented while line 7 deleted.
- The testing version can ve visualized in my forked repo. [willianpaixao.github.io/Sensor-Watch/](https://willianpaixao.github.io/Sensor-Watch/) Will remove after merge too.
- I also took the freedom to move the Makefile down to the same level as `app.c` as standard. There was no need having in `make/` folder if the compiled files were already going to `build`.
- As for the tag, we can leave for the next PR, since it's still unclear what exactly you want to build and expose. To my knowledge, there's no one firmware rather sample apps. Let's have a discussion about that.

**Comment by joeycastillo** [comment]
I will aim to take a look at this next week! (tomorrow I'm hitting the road, driving home for the holidays). 

> To my knowledge, there's no one firmware rather sample apps. Let's have a discussion about that.

The `movement` application, in the root of the repository, is the main firmware for the watch. The apps in `apps` are either leftovers from a time when I lacked a plan for a unified firmware, or one-off tests that will eventually be removed. `accelerometer-test`, for example, I can delete now, and `spi-test` is only there to test the SPI controller; once that code is written into the watch library, it can be deleted too. 

I think the goal for releases should be to just build the Movement UF2, but agree this is something we can hold off on for now.

**Comment by willianpaixao** [comment]
> tomorrow I'm hitting the road, driving home for the holidays

Happy holidays! 🎅🏾 

> The movement application, in the root of the repository, is the main firmware for the watch.

I just saw that, guess it's new code.
Ok, will update the pipeline to build the movement app.

**Comment by joeycastillo** [comment]
This is great, thanks again! Merging now, we can figure out the Movement stuff later.

**Comment by willianpaixao** [comment]
Just to a heads up, make sure that the [settings](joeycastillo) are set as the screenshot.

Screenshot_20211214_181109

**Comment by willianpaixao** [comment]
Uhu! https://joeycastillo.github.io/Sensor-Watch/

**Pull request merged**
